

spring:
  application:
    name: api-auth


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/
    registry-fetch-interval-seconds: 30

  instance:
    lease-renewal-interval-in-seconds: 30


---
server:
  port: 8866

spring:
  profiles: test1
---
server:
  port: 8877
spring:
  profiles: test2